import os


def env_bool(name, default):
    value = os.environ.get(name, default).lower()
    if value not in ("true", "false"):
        raise ValueError(name + " must be true or false")
    return value == "true"


def env_float(name, default):
    return float(os.environ.get(name, default))


def env_int(name, default):
    return int(os.environ.get(name, default))


FRAME_WIDTH = env_int("FRAME_WIDTH", "640")
FRAME_HEIGHT = env_int("FRAME_HEIGHT", "480")
CAMERA_BACKEND = os.environ.get("CAMERA_BACKEND", "auto").lower()
PICAMERA2_SWAP_RED_BLUE = env_bool("PICAMERA2_SWAP_RED_BLUE", "true")
HEADLESS_REQUEST = os.environ.get("HEADLESS", "auto").lower()
HEADLESS = (
    HEADLESS_REQUEST == "true"
    or (HEADLESS_REQUEST == "auto" and os.name != "nt" and not os.environ.get("DISPLAY"))
)
if HEADLESS_REQUEST not in ("auto", "true", "false"):
    raise ValueError("HEADLESS must be auto, true, or false")

ENABLE_ACTUATORS = env_bool("ENABLE_ACTUATORS", "false")
ENABLE_THROTTLE = env_bool("ENABLE_THROTTLE", "false")
THROTTLE_ALLOW_REVERSE = env_bool("THROTTLE_ALLOW_REVERSE", "false")
THROTTLE_NEUTRAL_US = env_int("THROTTLE_NEUTRAL_US", "1500")
THROTTLE_FORWARD_US = env_int("THROTTLE_FORWARD_US", "1600")
THROTTLE_REVERSE_US = env_int("THROTTLE_REVERSE_US", "1400")
THROTTLE_HARD_LIMIT = env_float("THROTTLE_HARD_LIMIT", "0.12")
THROTTLE_MIN_ACTIVE = env_float("THROTTLE_MIN_ACTIVE", "0.06")
MAX_TRIAL_THROTTLE = env_float("MAX_TRIAL_THROTTLE", "0.10")
MOTOR_STEERING_MIX = env_float("MOTOR_STEERING_MIX", "0.08")
MOTOR_OUTPUTS = (
    ("front_left", env_int("MOTOR_FRONT_LEFT_CHANNEL", "0"), env_float("MOTOR_FRONT_LEFT_SIGN", "1")),
    ("front_right", env_int("MOTOR_FRONT_RIGHT_CHANNEL", "1"), env_float("MOTOR_FRONT_RIGHT_SIGN", "1")),
    ("rear_left", env_int("MOTOR_REAR_LEFT_CHANNEL", "2"), env_float("MOTOR_REAR_LEFT_SIGN", "1")),
    ("rear_right", env_int("MOTOR_REAR_RIGHT_CHANNEL", "3"), env_float("MOTOR_REAR_RIGHT_SIGN", "1")),
)

TUI_ENABLED = env_bool("TUI", "true")
TUI_INTERVAL = env_float("TUI_INTERVAL", "0.10")
TELEMETRY_INTERVAL = env_float("TELEMETRY_INTERVAL", "0.25")

AUTO_CALIBRATE = env_bool("AUTO_CALIBRATE", "true")
AUTO_CALIBRATION_INTERVAL = env_float("AUTO_CALIBRATION_INTERVAL", "1.0")
AUTO_CALIBRATION_MAX_COLORS = env_int("AUTO_CALIBRATION_MAX_COLORS", "8")
AUTO_CALIBRATION_MIN_AREA_RATIO = env_float("AUTO_CALIBRATION_MIN_AREA_RATIO", "0.006")
AUTO_CALIBRATION_SATURATION_MIN = env_int("AUTO_CALIBRATION_SATURATION_MIN", "35")
AUTO_CALIBRATION_VALUE_MIN = env_int("AUTO_CALIBRATION_VALUE_MIN", "70")
AUTO_CALIBRATION_HUE_PADDING = env_int("AUTO_CALIBRATION_HUE_PADDING", "8")
AUTO_CALIBRATION_SATURATION_PADDING = env_int("AUTO_CALIBRATION_SATURATION_PADDING", "45")
AUTO_CALIBRATION_VALUE_PADDING = env_int("AUTO_CALIBRATION_VALUE_PADDING", "45")
AUTO_CALIBRATION_MERGE_HUE_DISTANCE = env_int("AUTO_CALIBRATION_MERGE_HUE_DISTANCE", "10")
KNOWN_COLOR_HUE_PADDING = env_int("KNOWN_COLOR_HUE_PADDING", "12")
KNOWN_COLOR_SATURATION_MIN = env_int("KNOWN_COLOR_SATURATION_MIN", "45")
KNOWN_COLOR_VALUE_MIN = env_int("KNOWN_COLOR_VALUE_MIN", "60")
MIN_BALL_AREA_RATIO = env_float("MIN_BALL_AREA_RATIO", "0.004")
MIN_BALL_AREA_TOP_SCALE = env_float("MIN_BALL_AREA_TOP_SCALE", "0.25")
MAX_BALL_AREA_RATIO = env_float("MAX_BALL_AREA_RATIO", "0.15")
MIN_BALL_CIRCULARITY = env_float("MIN_BALL_CIRCULARITY", "0.48")
MIN_BALL_CIRCLE_FILL = env_float("MIN_BALL_CIRCLE_FILL", "0.50")
TRIANGLE_APPROX_EPSILON = env_float("TRIANGLE_APPROX_EPSILON", "0.04")

CONE_HUE_MIN = env_int("CONE_HUE_MIN", "3")
CONE_HUE_MAX = env_int("CONE_HUE_MAX", "22")
CONE_SATURATION_MIN = env_int("CONE_SATURATION_MIN", "120")
CONE_VALUE_MIN = env_int("CONE_VALUE_MIN", "80")
CONE_VALUE_MAX = env_int("CONE_VALUE_MAX", "245")

TARGET_DISTANCE_WEIGHT = env_float("TARGET_DISTANCE_WEIGHT", "0.75")
TARGET_CLUSTER_WEIGHT = env_float("TARGET_CLUSTER_WEIGHT", "0.25")
TARGET_AREA_WEIGHT = env_float("TARGET_AREA_WEIGHT", "0.08")
TARGET_CENTER_WEIGHT = env_float("TARGET_CENTER_WEIGHT", "0.03")
TARGET_CLUSTER_RADIUS_RATIO = env_float("TARGET_CLUSTER_RADIUS_RATIO", "0.22")
TARGET_LOCK_RADIUS_RATIO = env_float("TARGET_LOCK_RADIUS_RATIO", "0.18")
TARGET_SWITCH_MARGIN = env_float("TARGET_SWITCH_MARGIN", "0.18")
TARGET_SWITCH_FRAMES = env_int("TARGET_SWITCH_FRAMES", "3")
TARGET_HOLD_SECONDS = env_float("TARGET_HOLD_SECONDS", "0.35")
TARGET_SMOOTHING = env_float("TARGET_SMOOTHING", "0.35")
STEERING_SLEW_RATE = env_float("STEERING_SLEW_RATE", "2.0")
STEERING_GAIN = env_float("STEERING_GAIN", "1.25")
STEERING_DEADBAND = env_float("STEERING_DEADBAND", "0.06")
CLOSE_BALL_AREA_RATIO = env_float("CLOSE_BALL_AREA_RATIO", "0.18")
LOST_TARGET_TIMEOUT = env_float("LOST_TARGET_TIMEOUT", "0.5")

# Linux gamepad configuration. Defaults follow the common evdev gamepad map.
CONTROLLER_DEVICE = os.environ.get("CONTROLLER_DEVICE", "auto")
CONTROLLER_A_BUTTON = env_int("CONTROLLER_A_BUTTON", "304")
CONTROLLER_LEFT_X_AXIS = env_int("CONTROLLER_LEFT_X_AXIS", "0")
CONTROLLER_LEFT_Y_AXIS = env_int("CONTROLLER_LEFT_Y_AXIS", "1")
CONTROLLER_RIGHT_X_AXIS = env_int("CONTROLLER_RIGHT_X_AXIS", "3")
CONTROLLER_RIGHT_Y_AXIS = env_int("CONTROLLER_RIGHT_Y_AXIS", "4")
CONTROLLER_DEADZONE = env_float("CONTROLLER_DEADZONE", "0.10")
CONTROLLER_INVERT_Y = env_bool("CONTROLLER_INVERT_Y", "true")
